package com.reeva.backend.expense;

public enum AiDecision {
    AUTO_APPROVED,
    READY_FOR_MANAGER,
    NEEDS_EMPLOYEE_CORRECTION,
    REJECTED_BY_POLICY,
    REJECTED_BY_FISCAL_VALIDATION,
    PENDING_MANUAL_REVIEW,
    DUPLICATE_REJECTED
}

